/*
Eden Hotel Group is a new player in the luxury hotel industry worldwide, based in Toronto, Canada. It has different brands in North America providing luxury 5-star accommodation, restaraunt's food and berage service 
and banquet catering. This new hotel group has been expanding further in Canada (reached 20 properties), the US (15), Mexico (8) and recently in West Europe, starting with City Hotels 
in Paris, France and Lausanne, Switzerland. Due to its growing brands, properties, employees, guests, customers and transactions, it requires a well-developed database to manage its business.


-- Tables:
Hotel_Brand: | ID | CITY_HOTEL_ID | EMPLOYEE_ID |
City_Hotel: | CITY_HOTEL_ID | CITY_HOTEL_NAME | CITY_HOTEL_BRAND | CITY_HOTE_ADDRESS |
Employee: | EMPLOYEE_ID | EMPLOYEE_NAME | DATE_OF_BIRTH | CITY_HOTEL_ID | TITLE | 
Services: | SERVICE_ID | SERVICE_NAME | PRICE | SERVICE_TYPE | 
Customer: | CUSTOMER_ID | CUSTOMER_NAME | CUSTOMER_DOB | CUSTOMER_COMPANY | CUSTOMER_CREDIT_CARD | CUSTOMER_ADDRESS | TRANSACTION_ID | CUSTOMER_BOOKING_ID |
Guest: | GUEST_ID | GUEST_NAME | GUEST_DOB | GUEST_COMPANY | GUEST_CREDIT_CARD  | GUEST_ADDRESS | TRANSACTION_ID  | CUSTOMER_BOOKING_ID  |
Supplier: | SUPPLIER_ID  | SUPPLIER_NAME | PURCHASE_ORDER  | PURCHASE_TYPE | 
Orders: | ORDER_ID | SUPPLIER_ID | CUSTOMER_ID | PRODUCT_ID | PRIMARY KEY |
*/

CREATE DATABASE Eden_Hotel_Group_Database;
use Eden_Hotel_Group_Database;
CREATE TABLE Hotel_Brand
 ( ID NUMERIC CONSTRAINT ID_NN NOT NULL,
CITY_HOTEL_ID NUMERIC (6,0),
EMPLOYEE_ID NUMERIC (6,0),
PRIMARY KEY (ID),
 );

CREATE TABLE City_Hotel
( CITY_HOTEL_ID NUMERIC (6,0) CONSTRAINT CITY_HOTEL_ID_NN NOT NULL ,
 CITY_HOTEL_NAME VARCHAR (30),
 CITY_HOTEL_BRAND VARCHAR (30),
 CITY_HOTEL_ADDRESS VARCHAR (40),
 PRIMARY KEY (CITY_HOTEL_ID),
 );

CREATE TABLE Employee
 ( EMPLOYEE_ID NUMERIC (6,0) CONSTRAINT EMPLOYEE_ID_NN NOT NULL,
EMPLOYEE_NAME VARCHAR (30),
DATE_OF_BIRTH VARCHAR (35),
CITY_HOTEL_ID NUMERIC (6,0),
TITLE VARCHAR(50),
PRIMARY KEY (EMPLOYEE_ID),
 );

CREATE TABLE Services
( SERVICE_ID NUMERIC (10,0) CONSTRAINT SERVICE_ID_NN NOT NULL,
 SERVICES_NAME VARCHAR (30),
 SERVICES_PRICE NUMERIC (6,0),
 SERVICES_TYPE VARCHAR (15),
 PRIMARY KEY (SERVICE_ID),
 );

CREATE TABLE Customer
( CUSTOMER_ID NUMERIC (6,0) CONSTRAINT CUSTOMER_ID_NN NOT NULL,
 CUSTOMER_NAME VARCHAR (30),
 CUSTOMER_DOB VARCHAR (30),
 CUSTOMER_COMPANY VARCHAR (30),
 CUSTOMER_CREDIT_CARD NUMERIC (20),
 CUSTOMER_ADDRESS VARCHAR (40),
 TRANSACTION_ID NUMERIC (6,0),
 CUSTOMER_BOOKING_ID NUMERIC (10),
PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE Guest
( GUEST_ID NUMERIC (6,0) CONSTRAINT GUEST_ID_NN NOT NULL,
 GUEST_NAME VARCHAR (30),
 GUEST_DOB VARCHAR (30),
 GUEST_COMPANY VARCHAR (30),
 GUEST_CREDIT_CARD NUMERIC (20),
 GUEST_ADDRESS VARCHAR (40),
 TRANSACTION_ID NUMERIC (6,0),
 CUSTOMER_BOOKING_ID NUMERIC (10), 
PRIMARY KEY (GUEST_ID)
);

CREATE TABLE Supplier
( SUPPLIER_ID NUMERIC (6,0) CONSTRAINT SUPPLIER_ID_NN NOT NULL,
 SUPPLIER_NAME VARCHAR (20),
PURCHASE_ORDER NUMERIC (10,0),
PURCHASE_TYPE VARCHAR (20),
PRIMARY KEY (SUPPLIER_ID),
);

CREATE TABLE Orders
( ORDER_ID NUMERIC (6,0) CONSTRAINT ORDER_ID_NN NOT NULL,
 SUPPLIER_ID NUMERIC (6,0),
CITY_HOTEL_ID NUMERIC (6,0),
PRODUCT_ID NUMERIC(10,0),
PRIMARY KEY (ORDER_ID),
FOREIGN KEY (SUPPLIER_ID) REFERENCES Supplier(SUPPLIER_ID),
FOREIGN KEY (CITY_HOTEL_ID) REFERENCES City_Hotel(CITY_HOTEL_ID),
FOREIGN KEY (SERVICE_ID) REFERENCES Services(SERVICE_ID),
);

ALTER TABLE Hotel_Brand
ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES Employee(EMPLOYEE_ID);

ALTER TABLE City_Hotel
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES Product(PRODUCT_ID);

ALTER TABLE Employee
ADD FOREIGN KEY (CITY_HOTEL_ID) REFERENCES City_Hotel(CITY_HOTEL_ID);
